version: '3.8'
services:
  keycloak-db:
    image: postgres
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1312
      POSTGRES_DB: keycloak
      POSTGRES_SCHEMA: keycloak
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin1312
      KC_FEATURES: declarative-user-profile
    entrypoint: [ "/opt/keycloak/bin/kc.sh", "start-dev" ]
    ports:
      - "8080:8080"
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "28018:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://lodge1312:lodge420@accommodation-db:27017/
  accommodation-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: lodge1312
      MONGO_INITDB_ROOT_PASSWORD: lodge420
      MONGO_INITDB_DATABASE: accommodation-db
    ports:
      - "27101:27017"
    volumes:
      - accommodation-db-data:/data/db
      - ../entrypoint-initdb.d:/docker-entrypoint-initdb.d
  reservation-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: lodge1312
      MONGO_INITDB_ROOT_PASSWORD: lodge420
      MONGO_INITDB_DATABASE: reservation-db
    ports:
      - "27018:27017"
    volumes:
      - reservation-db-data:/data/db
      - ../entrypoint-initdb.d:/docker-entrypoint-initdb.d
  user-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: lodge1312
      MONGO_INITDB_ROOT_PASSWORD: lodge420
      MONGO_INITDB_DATABASE: user-db
    ports:
      - "27019:27017"
    volumes:
      - user-db-data:/data/db
      - ../entrypoint-initdb.d:/docker-entrypoint-initdb.d
  search-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: lodge1312
      MONGO_INITDB_ROOT_PASSWORD: lodge420
      MONGO_INITDB_DATABASE: search-db
    ports:
      - "27100:27017"
    volumes:
      - search-db-data:/data/db
      - ../entrypoint-initdb.d:/docker-entrypoint-initdb.d
volumes:
  accommodation-db-data:
    driver: local
  reservation-db-data:
    driver: local
  user-db-data:
    driver: local
  search-db-data:
    driver: local
  keycloak-db-data:
    driver: local